### ISSUE TITLE
qwx error report

### ISSUE THREAD

**Issue by maxadjsky** [xiangzhai/qwx#10]
我的openSuse版本是 13.1,一键安装后，运行qwx。图形界面点击之后，有程序运行，但是后台就消失了。命令行运行显示
qwx: symbol lookup error: /usr/lib64/libQt5Qml.so.5: undefined symbol: _ZN16QLoggingCategoryD1Ev
不知道还需要什么其他的信息吗，第一次提交，需要其他信息请联系maxadjsky#live.com

**Comment by xiangzhai** [comment]
Hi @maxadjsky 我给qt官方提个bug吧，Google到有类似的问题 https://together.jolla.com/question/63338/bug-screen-stays-black-after-reboot/

@hillwoodroc 13.1上“打包”的Qt版本是多少呀？

**Comment by hillwoodroc** [comment]
这个 bug 可以关闭了，就是 QT5 版本冲突的问题。和 qwx 无关。
