### ISSUE TITLE
可以整理一份完整的协议文档吗

### ISSUE THREAD

**Issue by biezhi** [xiangzhai/qwx#26]
当前协议文档中包含了旧的和wx2.qq.com
目前登陆后都跳转到wx2.qq.com下，作者现在的文档新的旧的都有，如果可以的话可以修改一份新的文档吗？
Qt程序如果有个可执行版本我也可以试试哈😀

**Comment by reverland** [comment]
[](http://img.vim-cn.com/dd/e58f9f5ba7b24544e9b00d4ad9b2005e78c18c.svg)

**Comment by reverland** [comment]
顺便图操公众号，简直难用。。。

**Comment by biezhi** [comment]
@reverland thanks

**Comment by reverland** [comment]
@biezhi 看这里：https://github.com/Urinx/WeixinBot
