### ISSUE TITLE
No my avatar in chat view

### ISSUE THREAD

**Issue by yangh** [xiangzhai/qwx#28]
![Uploading Screenshot from 2016-03-25 21-30-25.png…]()

Please refer to the attached screen shot.

**Comment by yangh** [comment]
qrc:/qml/IView.qml:7:2: QML Image: Error downloading http://qr.liantu.com/api.php?text=xxx-xxx&logo=https://open.weixin.qq.com/zh_CN/htmledition/res/assets/res-design-download/icon64_wx_logo.png - server replied: Internal Server Error

**Comment by xiangzhai** [comment]
@yangh IView requires KF5Prison, and please update README about ubuntu dependence, thanks a lot!
