### ISSUE TITLE
Archlinux need extra-cmake-modules

### ISSUE THREAD

**Issue by VliuPro** [xiangzhai/qwx#38]
还有，中文输入不了0.0 ?

用的 fcitx-sogoupinyin

还是要设置什么？

**Comment by xiangzhai** [comment]
> 中文输入不了

QML问题？你在KDE5下konsole可以输入中文否？

**Comment by VliuPro** [comment]
@xiangzhai 桌面环境是Gnome。。。

**Comment by xiangzhai** [comment]
GNOME桌面环境请使用[qt5分支](https://github.com/xiangzhai/qwx/tree/qt5)
