### ISSUE TITLE
普华龙芯版编译出错

### ISSUE THREAD

**Issue by MISWANGHONGGANG** [xiangzhai/qwx#39]
内核版本：Linux isoft 3.10.105-13.mips64el #1 SMP PREEMPT Fri Jul 14 11:41:46 CST 2017 mips64 mips64 mips64 GNU/Linux
QT版本：qt-4.8.6-15.fc21.loongson.2.mips64el 
错误信息：
/home/xinxing/下载/qwx-qt5/src/qwxuuid.cpp: 在成员函数‘void QwxUUID::get()’中:
/home/xinxing/下载/qwx-qt5/src/qwxuuid.cpp:33:10: **错误**：对‘QTimer::singleShot(int, QwxUUID*, QwxUUID::get()::<lambda()>)’的调用没有匹配的函数
         });
          ^
/home/xinxing/下载/qwx-qt5/src/qwxuuid.cpp:33:10: 附注：备选是：
In file included from /usr/include/qt5/QtCore/QTimer:1:0,
                 from /home/xinxing/下载/qwx-qt5/src/qwxuuid.cpp:5:
/usr/include/qt5/QtCore/qtimer.h:81:17: 附注：static void QTimer::singleShot(int, const QObject*, const char*)
     static void singleShot(int msec, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:81:17: 附注：  no known conversion for argument 3 from ‘QwxUUID::get()::<lambda()>’ to ‘const char*’
/usr/include/qt5/QtCore/qtimer.h:82:17: 附注：static void QTimer::singleShot(int, Qt::TimerType, const QObject*, const char*)
     static void singleShot(int msec, Qt::TimerType timerType, const QObject *receiver, const char *member);
                 ^
/usr/include/qt5/QtCore/qtimer.h:82:17: 附注： 备选需要 4 实参，但提供了 3 个
src/CMakeFiles/qwx.dir/build.make:270: recipe for target 'src/CMakeFiles/qwx.dir/qwxuuid.cpp.o' failed
make.orig[2]: *** [src/CMakeFiles/qwx.dir/qwxuuid.cpp.o] Error 1
CMakeFiles/Makefile2:222: recipe for target 'src/CMakeFiles/qwx.dir/all' failed
make.orig[1]: *** [src/CMakeFiles/qwx.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make.orig: *** [all] Error 2

**Comment by xiangzhai** [comment]
> QT版本：qt-4.8.6-15.fc21.loongson.2.mips64el

qt4不支持，请打包qt5，谢谢！
