### ISSUE TITLE
标签“我”无法显示

### ISSUE THREAD

**Issue by xiangzhai** [xiangzhai/qwx#6]

**Comment by xiangzhai** [comment]
Hi @hillwoodroc 已修正 https://github.com/xiangzhai/qwx/commit/04b0d7d549b3655ade2b53c87432b7985c839624

请测试 ;)

标签“我”的页面内容还在“建设当中” ;)

**Comment by hillwoodroc** [comment]
你把我的邮箱写错了，是 hillwood#opensuse.org 或者 hillwoodroc#gmail.com

**Comment by xiangzhai** [comment]
不好意思啦 |||
