### ISSUE TITLE
get 监听会话 Ret 1100 然后心跳就无法再同步了

### ISSUE THREAD

**Issue by xiangzhai** [xiangzhai/qwx#8]

**Comment by xiangzhai** [comment]
1. 将GetMsg放在"监听会话"的onNewMsg里
2. 监听会话Monitor将每3秒“查看”一下是否有新消息

**Comment by lestchun** [comment]
你好  现在好像 如果不用心跳包  循环去 取消息的话  会 自动掉线 你们有解决吗

**Comment by xiangzhai** [comment]
@lestchun 你看看这次提交 https://github.com/xiangzhai/qwx/commit/b1cf4148b4058327a7f211621c51cc4655e56714 参考协议 https://github.com/xiangzhai/qwx/blob/master/doc/protocol.md#get-%E7%9B%91%E5%90%AC%E4%BC%9A%E8%AF%9D

**Comment by reverland** [comment]
似乎是synccheck作为一个被服务器hold住的长连接，一旦服务器有新的消息推送就通过该连接返回并断开，并开始下一个被hold住的syncheck请求。

这样，每次syncheck都会返回一个synckey，每次都更新这个synckey来进行synccheck或者webwxsync的过程。

所以，觉得不用去每3秒去请求检查一下，等着synccheck断开，就webwxsync或开始下一次syncheck应该就行。我试着实现了下感觉差不多。

https://github.com/HalfdogStudio/wechat-user-bot/blob/master/test.js#L412

web微信里写的synccheck的timeout给的是35000，服务器则会在27000ms左右一定关闭连接。

**Comment by xiangzhai** [comment]
@reverland coooooooool 我学习学习~

**Comment by HanSon** [comment]
@reverland 文件现在已经不存在了，能告知最新位置吗？

**Comment by HanSon** [comment]
@reverland 已经找到，我也尝试一下这个方法
